
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hch
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
server:
  port: 8080